from enum import Enum


class StateCode(Enum):
    AL = "AL"
    AK = "AK"
    AZ = "AZ"
    AR = "AR"
    CA = "CA"
    CO = "CO"
    CT = "CT"
    DE = "DE"
    FL = "FL"
    GA = "GA"
    HI = "HI"
    ID = "ID"
    IL = "IL"
    IN = "IN"
    IA = "IA"
    KS = "KS"
    KY = "KY"
    LA = "LA"
    ME = "ME"
    MD = "MD"
    MA = "MA"
    MI = "MI"
    MN = "MN"
    MS = "MS"
    MO = "MO"
    MT = "MT"
    NE = "NE"
    NV = "NV"
    NH = "NH"
    NJ = "NJ"
    NM = "NM"
    NY = "NY"
    NC = "NC"
    ND = "ND"
    OH = "OH"
    OK = "OK"
    OR = "OR"
    PA = "PA"
    RI = "RI"
    SC = "SC"
    SD = "SD"
    TN = "TN"
    TX = "TX"
    UT = "UT"
    VT = "VT"
    VA = "VA"
    WA = "WA"
    WV = "WV"
    WI = "WI"
    WY = "WY"


class Chamber(Enum):
    LOWER = "lower"
    UPPER = "upper"


class OnDuplicate(Enum):
    IGNORE = "ignore"
    MERGE = "merge"


class BillAction(str, Enum):
    INTRODUCED_LOWER = "introduced_lower"
    FIRST_READING_LOWER = "first_reading_lower"
    SECOND_READING_LOWER = "second_reading_lower"
    THIRD_READING_LOWER = "third_reading_lower"
    REFERRED_TO_COMMITTEE_LOWER = "referred_to_committee_lower"
    REPORTED_FROM_COMMITTEE_LOWER = "reported_from_committee_lower"
    AMENDED_LOWER = "amended_lower"
    ACCEPTED_LOWER = "accepted_lower"
    REJECTED_LOWER = "rejected_lower"
    TABLED_LOWER = "tabled_lower"
    REMOVED_FROM_TABLE_LOWER = "removed_from_table_lower"

    INTRODUCED_UPPER = "introduced_upper"
    FIRST_READING_UPPER = "first_reading_upper"
    SECOND_READING_UPPER = "second_reading_upper"
    THIRD_READING_UPPER = "third_reading_upper"
    REFERRED_TO_COMMITTEE_UPPER = "referred_to_committee_upper"
    REPORTED_FROM_COMMITTEE_UPPER = "reported_from_committee_upper"
    AMENDED_UPPER = "amended_upper"
    ACCEPTED_UPPER = "accepted_upper"
    REJECTED_UPPER = "rejected_upper"
    TABLED_UPPER = "tabled_upper"
    REMOVED_FROM_TABLE_UPPER = "removed_from_table_upper"

    SENT_TO_UPPER = "sent_to_upper"
    SENT_TO_LOWER = "sent_to_lower"

    RETURNED_WITH_AMENDMENTS = "returned_with_amendments"
    CONFERENCE_COMMITTEE_APPOINTED = "conference_committee_appointed"
    CONFERENCE_COMMITTEE_REPORTED = "conference_committee_reported"

    CONCURRENCE_LOWER = "concurrence_lower"
    CONCURRENCE_UPPER = "concurrence_upper"

    AT_EXECUTIVE = "at_executive"
    SIGNED_BY_GOVERNOR = "signed_by_governor"
    BECAME_LAW_WITHOUT_SIGNATURE = "became_law_without_signature"
    LINE_ITEM_VETO = "line_item_veto"
    VETOED = "vetoed"
    VETO_OVERRIDE_PASSED = "veto_override_passed"
    VETO_OVERRIDE_FAILED = "veto_override_failed"

    ENACTED = "enacted"
    POSTPONED = "postponed"
    INDEFINITELY_POSTPONED = "indefinitely_postponed"
    WITHDRAWN = "withdrawn"
    RECONSIDERATION = "reconsideration"
